apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todo-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: todo-service
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: todo-mvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mvc
  namespace: default
  labels:
    app: todo-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mvc
  template:
    metadata:
      labels:
        app: todo-mvc
    spec:
      containers:
      - name: todo-mvc
        image: {{ .Values.imageBase }}{{ .Values.todo.imageTag }}
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
